service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminInitiateAuth"
            - "cognito-idp:AdminCreateUser"
            - "cognito-idp:AdminSetUserPassword"
          Resource: 
            - "*"
functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: dev-user-pool
        Schema:
          - AttributeDataType: String
            Name: email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
    UserClient:
          Type: AWS::Cognito::UserPoolClient
          Properties:
            ClientName: dev-user-pool-client
            GenerateSecret: false
            UserPoolId:
              Ref: UserPool
            AccessTokenValidity: 5
            IdTokenValidity: 5